Controllers/IletisimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CaptchaMvc.HtmlHelpers;
using BolumTer.Models;
using BolumTer.App_Class;


namespace BolumTer.Controllers
{
    public class IletisimController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(Feedback FormData)
        {

            if (this.IsCaptchaValid("Captcha is not valid"))
            {
                dbOp dbOp = new dbOp();
                dbOp.writeIletisim(FormData.localId, FormData.EMail, FormData.comment);
                return RedirectToAction("eywllh");
            }

            ViewBag.ErrMessage = "Hata: Resimdeki harfleri doğru girmelisin!";
            return View();
        }

        public ActionResult eywllh()
        {
            return View();
        }


    }
}

Views/Iletisim/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using CaptchaMvc.HtmlHelpers   
@using BolumTer;   
@using CaptchaMvc;   
   
@model BolumTer.Models.Feedback   
   
@{   
    ViewBag.Title = "Index";   
}   
   
@using (Html.BeginForm("Index","Iletisim")) {   


<script type='text/javascript'>
    $(function () {

        var local = window.localStorage;
        LocalId = local.getItem("LocalId");
        if (LocalId == null) {
            $("#cid").val("0");
        }
        if (LocalId != null) $("#cid").val(LocalId);
        console.log(LocalId);
    });
</script>
    <fieldset>   
        <legend>İletişim Formu</legend>   
   
<p>Her türlü görüş, öneri ve hata bildirimlerinizi bize yazın;</p>
        <div class="editor-label">   

                       
            <label>E-Posta :</label>
        </div>   
        <div class="editor-field">   
                <input id="cmail" style="width:44em" type="email" maxlength="200" name="EMail" required />


        </div>   
   <input id="cid" class="hidden" name="localId" value="2" />
        <div class="editor-label">   
                <label>İleti:</label>
        </div>   
        <div class="editor-field">   
                <textarea id="ccomment" name="comment" style="width:44em;height:15em;" maxlength="1000" required></textarea>
        </div>   
      
        @Html.Captcha(3)
         <br />   
        <p class="Error">  @ViewBag.ErrMessage </p>   
        <p>   
            <input type="submit" class="btn-custom" value="Gönder" />   
        </p>   
    </fieldset>  
<div style="margin-bottom:16em;"></div> 


}  

Views/Iletisim/eywllh.cshtml
@{
    ViewBag.Title = "eywllh";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model BolumTer.Models.Feedback   
   
@{   
    ViewBag.Title = "ThankYouPage";   
}   
   
<h2>Teşekkürler..</h2>   
   
<b>İletilerin için teşekkür ederiz.</b>  
<div style="margin-bottom:44em"></div>